(require 'diminish)

;; 表示を消す
(diminish 'helm-mode)
;; (diminish 'helm-gtags-mode)
(diminish 'ace-jump-mode)
;; (diminish 'volatile-highlights-mode)
;; (diminish 'yas-minor-mode)
;; (diminish 'yascroll-mode)
;; (diminish 'undo-tree-mode)
;; (diminish 'smartparens-mode)
;; (diminish 'smart-newline)
;; (diminish 'auto-complete-mode)
;; (diminish 'abbrev-mode)
;; (diminish 'eldoc-mode)

(when (require 'diminish nil t)
  (with-eval-after-load "isearch" (diminish 'isearch-mode))
  (with-eval-after-load "smooth-scroll" (diminish 'smooth-scroll-mode))
  (with-eval-after-load "whitespace" (diminish 'global-whitespace-mode))
  (with-eval-after-load "centered-cursor-mode"
    (diminish 'centered-cursor-mode))
  (with-eval-after-load "volatile-highlights"
    (diminish 'volatile-highlights-mode))
  (with-eval-after-load "aggressive-indent"
    (diminish 'aggressive-indent-mode " Ai"))
  (with-eval-after-load "emmet-mode" (diminish 'emmet-mode " e"))
  (with-eval-after-load "abbrev" (diminish 'abbrev-mode " a"))
  (with-eval-after-load "yasnippet" (diminish 'yas-minor-mode " y"))
  (with-eval-after-load "doxymacs" (diminish 'doxymacs-mode " d"))
  (with-eval-after-load "auto-complete-mode" (diminish 'auto-complete-mode " ac"))
  (with-eval-after-load "undo-tree-mode" (diminish 'undo-tree-mode " uc"))
  (with-eval-after-load "rainbow-mode" (diminish 'rainbow-mode))
;;;  (with-eval-after-load "helm" (diminish 'helm-mode " H"))
  )
;; (add-hook 'c-mode-hook '(lambda () (setq mode-name "C")))
;; (add-hook 'c++-mode-hook '(lambda () (setq mode-name "C++")))
;; (add-hook 'csharp-mode-hook '(lambda () (setq mode-name "C#")))
(add-hook 'emacs-lisp-mode-hook '(lambda () (setq mode-name "el")))
(add-hook 'perl-mode-hook '(lambda () (setq mode-name "pl")))
(add-hook 'web-mode-hook '(lambda () (setq mode-name "W")))
(add-hook 'lisp-interaction-mode-hook '(lambda () (setq mode-name "Lisp")))
