(when (require 'diminish nil t)
  (with-eval-after-load "isearch" (diminish 'isearch-mode " I"))
  (with-eval-after-load "smooth-scroll" (diminish 'smooth-scroll-mode))
  (with-eval-after-load "whitespace" (diminish 'global-whitespace-mode))
  (with-eval-after-load "centered-cursor-mode" (diminish 'centered-cursor-mode))
  (with-eval-after-load "volatile-highlights" (diminish 'volatile-highlights-mode))
  (with-eval-after-load "aggressive-indent" (diminish 'aggressive-indent-mode " AI"))
  (with-eval-after-load "emmet-mode" (diminish 'emmet-mode " E"))
  (with-eval-after-load "abbrev" (diminish 'abbrev-mode " A"))
  (with-eval-after-load "yasnippet" (diminish 'yas-minor-mode " Y"))
  (with-eval-after-load "doxymacs" (diminish 'doxymacs-mode " D"))
  (with-eval-after-load "auto-complete" (diminish 'auto-complete-mode " AC"))
  (with-eval-after-load "rainbow-mode" (diminish 'rainbow-mode " R"))
  (with-eval-after-load "undo-tree" (diminish 'undo-tree-mode " UT"))
  (with-eval-after-load "eldoc" (diminish 'eldoc-mode " EL"))
  (with-eval-after-load "helm-gtags" (diminish 'helm-gtags-mode " HG"))
  (with-eval-after-load "flycheck" (diminish 'flycheck-mode " FC"))
  (with-eval-after-load "helm" (diminish 'helm-mode " H")))

  (add-hook 'emacs-lisp-mode-hook '(lambda () (setq mode-name "el")))
  (add-hook 'perl-mode-hook '(lambda () (setq mode-name "pl")))
  (add-hook 'web-mode-hook '(lambda () (setq mode-name "w")))
  (add-hook 'lisp-interaction-mode-hook '(lambda () (setq mode-name "li")))
  (add-hook 'php-mode-hook '(lambda () (setq mode-name "php")))
  (add-hook 'ruby-mode-hook '(lambda () (setq mode-name "rb")))
