(use-package helm-config)
(use-package helm)
(helm-mode +1)

(global-set-key (kbd "M-x") 'helm-M-x)
(global-set-key (kbd "C-x C-f") 'helm-find-files)
(global-set-key (kbd "C-x C-r") 'helm-recentf)
(global-set-key (kbd "C-x C-o") 'helm-resume)
(global-set-key (kbd "M-y") 'helm-show-kill-ring)
(global-set-key (kbd "C-x b") 'helm-buffers-list)
(global-set-key (kbd "C-x C-b") 'helm-bookmarks)
(global-set-key (kbd "C-x C-d") 'helm-descbinds)
(define-key helm-find-files-map (kbd "TAB") 'helm-execute-persistent-action)

(setq helm-buffer-max-length 50)
