;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        cua-copy-region
        cua-set-rectangle-mark
        helm-show-kill-ring
        kmacro-end-and-call-macro
        mc/mark-all-dwim-or-expand-region
        mc/mark-all-dwim-or-mark-sexp
        seq-end
        seq-home
        yank-rectangle
        ))

(setq mc/cmds-to-run-once
      '(
        c-electric-paren
        cua--shift-control-c-prefix
        cua-paste
        mark-paragraph
        yas-expand
        ))
